- name: print hello world
  ansible.builtin.debug:
    msg: Hello World

- name: print URL
  ansible.builtin.debug:
    msg: URL - {{ EXAMPLE }}

- name: Demo on register variables
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: check package
      ansible.builtin.dnf:
        name: zlib
        state: installed
      register: out

- name: Print out
  ansible.builtin.debug:
    msg: "{{ out }}"