- name: Demo on conditions
  hosts: localhost
  connection: local
  tasks:
    - name: print OS PRABHAS
      ansible.builtin.debug:
        msg: PRABHAS

    - name: print OS Ubuntu
      ansible.builtin.debug:
        msg: Ubuntu