- name: Demo on variables
  hosts: localhost
  connection: local
  vars:
    URL: vars.google.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL -  {{ URL }} # Accessing a variable in ansible.

- name: Demo on role variables
  hosts: localhost
  connection: local
  roles:
    - sample