- name: Demo on variables
  hosts: localhost
  connection: local
  vars:
    URL: vars.google.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL -  {{ URL }} # Accessing a variable in ansible.

- name: Demo on role variables
  hosts: localhost
  connection: local
  roles:
    - sample


- name: Demo on register variables
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: check package
      ansible.builtin.dnf:
        name: python
        state: installed
      register: out

    - name: Print out
      ansible.builtin.debug:
        msg: "{{ out }}"
